# Generated by Django 5.0.6 on 2024-06-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='coins',
            field=models.JSONField(default=None),
        ),
    ]
